### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by YoussefLagtab** [Sisteem/readline#3]
running `make` result the following error:

`Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [readline] Error 1`

**Comment by medwali** [comment]
@YoussefLagtab you need to install `objcopy` with `brew`:
```
BREW_HOME="$(brew config | sed -n '/HOMEBREW_PREFIX/{s/.*: //;p;}')"
brew install binutils
ln -s "$BREW_HOME"/opt/binutils/bin/objcopy "$BREW_HOME"/bin/objcopy
```
